package org.mongeez.dao.factory

import com.mongodb.client.MongoCollection
import com.mongodb.client.model.Indexes.ascending
import org.bson.Document
import org.mongeez.dao.ChangeSetAttribute

object MongeezDaoIndexConfigurer {
    fun configureIndexes(mongeezCollection: MongoCollection<Document>,
                         changeSetAttributes: List<ChangeSetAttribute>) {
        dropObsoleteChangeSetExecutionIndices(mongeezCollection)
        ensureChangeSetExecutionIndex(mongeezCollection, changeSetAttributes)
    }

    /**
     * Removes indices that were generated by versions before 0.9.3, since they're not supported by MongoDB 2.4+
     */
    private fun dropObsoleteChangeSetExecutionIndices(mongeezCollection: MongoCollection<Document>) {
        val indexName = "type_changeSetExecution_file_1_changeId_1_author_1_resourcePath_1"
        mongeezCollection.listIndexes()
                .filter { indexName == it.getString("name") }
                .forEach { mongeezCollection.dropIndex(it) }
    }

    private fun ensureChangeSetExecutionIndex(mongeezCollection: MongoCollection<Document>,
                                              changeSetAttributes: List<ChangeSetAttribute>) {
        val attributeNames = listOf("type") + changeSetAttributes.map { it.dbFieldName }
        mongeezCollection.createIndex(ascending(attributeNames))
    }
}
